spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: SDZTDNWVGSNQXOYD
    # 发送者邮箱地址
    username: 17804331763@163.com
    # 端口（不同邮箱端口号不同）
    port: 25
  redis:
    #超时时间
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
server:
  port: 8082
