spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: SDZTDNWVGSNQXOYD
    # 发送者邮箱地址
    username: 17804331763@163.com
    # 端口（不同邮箱端口号不同）
    port: 25

server:
  port: 8082
